import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df1 = pd.read_csv('dosya1.csv')
df2 = pd.read_csv('dosya2.csv')
df3 = pd.read_csv('dosya3.csv')
df4 = pd.read_csv('dosya4.csv')
merged_df = pd.concat([df1, df2, df3, df4], ignore_index=True)
summary_stats = merged_df.describe()
print(summary_stats)
plt.figure(figsize=(10, 6))
sns.histplot(merged_df['MMLU avg'], bins=20, kde=True)
plt.title('MMLU Avg Dağılımı')
plt.xlabel('MMLU Avg')
plt.ylabel('Frekans')
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(data=merged_df, x='Year', y='MMLU avg', hue='Organization', palette='viridis')
plt.title('Yıl ve MMLU Avg Arasındaki İlişki')
plt.xlabel('Yıl')
plt.ylabel('MMLU Avg')
plt.legend(title='Organization', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()
plt.figure(figsize=(10, 6))
sns.histplot(merged_df['Training computation (petaFLOP)'], bins=20, kde=True)
plt.title('Training Computation (petaFLOP) Dağılımı')
plt.xlabel('Training computation (petaFLOP)')
plt.ylabel('Frekans')
plt.show()

